apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cert-manager
      version: "v1.13.3"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Global configuration
    global:
      leaderElection:
        namespace: cert-manager
    
    # Install CRDs
    installCRDs: true
    
    # Controller configuration
    replicaCount: 2
    
    # Resource configuration
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    
    # Pod security context
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    
    # Service account
    serviceAccount:
      create: true
      name: cert-manager
    
    # RBAC
    rbac:
      create: true
    
    # Webhook configuration
    webhook:
      replicaCount: 2
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    
    # CA Injector configuration
    cainjector:
      replicaCount: 2
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    
    # Prometheus monitoring
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        prometheusInstance: default
        targetPort: 9402
        path: /metrics
        interval: 60s
        scrapeTimeout: 30s
        labels:
          app: cert-manager
    
    # Node selector for control plane nodes (optional)
    nodeSelector: {}
    
    # Tolerations for control plane nodes (optional)
    tolerations: []
    
    # Affinity rules
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - cert-manager
            topologyKey: kubernetes.io/hostname
    
    # Extra arguments
    extraArgs:
      - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
      - --dns01-recursive-nameservers-only
      - --enable-certificate-owner-ref=true
    
    # Feature gates
    featureGates: ""
---
# ServiceMonitor for Prometheus monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  namespace: monitoring
  labels:
    app: cert-manager
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
  endpoints:
  - port: tcp-prometheus-servicemonitor
    interval: 60s
    path: /metrics
  namespaceSelector:
    matchNames:
    - cert-manager
---
# Grafana Dashboard ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-dashboard
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  cert-manager-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "cert-manager Certificate Management",
        "tags": ["cert-manager", "certificates", "security"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Certificate Status",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(certmanager_certificate_ready_status{condition=\"True\"}) by (name, namespace)",
                "legendFormat": "Ready Certificates",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "thresholds"
                },
                "thresholds": {
                  "steps": [
                    {"color": "red", "value": null},
                    {"color": "green", "value": 1}
                  ]
                }
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Certificate Expiry",
            "type": "graph",
            "targets": [
              {
                "expr": "(certmanager_certificate_expiration_timestamp_seconds - time()) / 86400",
                "legendFormat": "{{name}} - {{namespace}} (days)",
                "refId": "A"
              }
            ],
            "yAxes": [
              {
                "label": "Days until expiry",
                "min": 0
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
          },
          {
            "id": 3,
            "title": "ACME Challenge Success Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(rate(certmanager_acme_client_request_count{status=\"success\"}[5m])) / sum(rate(certmanager_acme_client_request_count[5m]))",
                "legendFormat": "Success Rate",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percentunit",
                "thresholds": {
                  "steps": [
                    {"color": "red", "value": null},
                    {"color": "yellow", "value": 0.8},
                    {"color": "green", "value": 0.95}
                  ]
                }
              }
            },
            "gridPos": {"h": 8, "w": 24, "x": 0, "y": 8}
          }
        ],
        "time": {
          "from": "now-24h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }

