apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 24h
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: "0.9.11"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Global configuration
    global:
      # Image configuration
      imageRegistry: ""
      imagePullSecrets: []
    
    # Replica count for high availability
    replicaCount: 2
    
    # Image configuration
    image:
      repository: ghcr.io/external-secrets/external-secrets
      tag: v0.9.11
      pullPolicy: IfNotPresent
    
    # Resource configuration
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    # Security context
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      seccompProfile:
        type: RuntimeDefault
    
    # Pod security context
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
    
    # Service account
    serviceAccount:
      create: true
      name: external-secrets-operator
      annotations: {}
    
    # RBAC
    rbac:
      create: true
    
    # Service monitor for Prometheus
    serviceMonitor:
      enabled: true
      namespace: monitoring
      labels:
        app: external-secrets
        release: prometheus
      interval: 30s
      scrapeTimeout: 25s
    
    # Metrics configuration
    metrics:
      listen:
        port: 8080
      service:
        enabled: true
        port: 8080
    
    # Webhook configuration
    webhook:
      create: true
      replicaCount: 2
      image:
        repository: ghcr.io/external-secrets/external-secrets
        tag: v0.9.11
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
    
    # Cert controller configuration
    certController:
      create: true
      replicaCount: 1
      image:
        repository: ghcr.io/external-secrets/external-secrets
        tag: v0.9.11
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
    
    # Node selector
    nodeSelector: {}
    
    # Tolerations
    tolerations: []
    
    # Affinity rules
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - external-secrets
            topologyKey: kubernetes.io/hostname
    
    # Extra environment variables
    env: {}
    
    # Extra arguments
    extraArgs: {}
    
    # Priority class
    priorityClassName: ""
    
    # Pod disruption budget
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
---
# ServiceMonitor for Prometheus monitoring
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: external-secrets-operator
  namespace: monitoring
  labels:
    app: external-secrets
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
    - external-secrets-system
---
# Grafana Dashboard ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-secrets-dashboard
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
data:
  external-secrets-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "External Secrets Operator",
        "tags": ["external-secrets", "secrets", "security"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Secret Sync Status",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(external_secrets_sync_calls_total{status=\"success\"}) by (name, namespace)",
                "legendFormat": "Successful Syncs",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "thresholds"
                },
                "thresholds": {
                  "steps": [
                    {"color": "red", "value": null},
                    {"color": "green", "value": 1}
                  ]
                }
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Sync Error Rate",
            "type": "stat",
            "targets": [
              {
                "expr": "sum(rate(external_secrets_sync_calls_total{status=\"error\"}[5m])) / sum(rate(external_secrets_sync_calls_total[5m]))",
                "legendFormat": "Error Rate",
                "refId": "A"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "unit": "percentunit",
                "thresholds": {
                  "steps": [
                    {"color": "green", "value": null},
                    {"color": "yellow", "value": 0.01},
                    {"color": "red", "value": 0.05}
                  ]
                }
              }
            },
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
          },
          {
            "id": 3,
            "title": "External Secrets by Provider",
            "type": "piechart",
            "targets": [
              {
                "expr": "count by (provider) (external_secrets_external_secret_info)",
                "legendFormat": "{{provider}}",
                "refId": "A"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 8}
          },
          {
            "id": 4,
            "title": "Sync Duration",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, sum(rate(external_secrets_sync_duration_seconds_bucket[5m])) by (le))",
                "legendFormat": "P95 Sync Duration",
                "refId": "A"
              }
            ],
            "yAxes": [
              {
                "label": "Duration (seconds)",
                "min": 0
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8}
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }

