apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: istio-system
  annotations:
    description: "Enable strict mTLS for all workloads in the mesh"
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: default
  annotations:
    description: "Enable strict mTLS for default namespace"
spec:
  mtls:
    mode: STRICT
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: default-deny
  namespace: istio-system
  annotations:
    description: "Default deny policy - explicit allow required"
spec:
  # Empty spec denies all traffic by default
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-ingress
  namespace: istio-system
  annotations:
    description: "Allow traffic from ingress gateway"
spec:
  selector:
    matchLabels:
      app: istio-proxy
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]

