apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-api-metrics
  namespace: monitoring
  labels:
    app: gateway-api
    release: prometheus
spec:
  selector:
    matchLabels:
      app: istio-proxy
  namespaceSelector:
    matchNames:
    - istio-system
    - default
  endpoints:
  - port: http-monitoring
    interval: 30s
    path: /stats/prometheus
    scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-mesh-metrics
  namespace: monitoring
  labels:
    app: istio-mesh
    release: prometheus
spec:
  selector:
    matchLabels:
      app: istiod
  namespaceSelector:
    matchNames:
    - istio-system
  endpoints:
  - port: http-monitoring
    interval: 15s
    path: /metrics
    scheme: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-proxy-metrics
  namespace: monitoring
  labels:
    app: istio-proxy
    release: prometheus
spec:
  selector:
    matchLabels:
      app: istio-proxy
  namespaceSelector:
    any: true
  endpoints:
  - port: http-envoy-prom
    interval: 30s
    path: /stats/prometheus
    scheme: http

