apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  labels:
    app: cert-manager
    environment: staging
spec:
  acme:
    # ACME server URL for Let's Encrypt staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    
    # Email address used for ACME registration
    email: admin@example.com  # Replace with your email
    
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: istio
    
    # Enable DNS-01 challenge provider for wildcard certificates
    - dns01:
        cloudflare:
          email: admin@example.com  # Replace with your Cloudflare email
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
      selector:
        dnsNames:
        - "*.dev.local"
        - "*.staging.local"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  labels:
    app: cert-manager
    environment: production
spec:
  acme:
    # ACME server URL for Let's Encrypt production
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email address used for ACME registration
    email: admin@example.com  # Replace with your email
    
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production
    
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: istio
    
    # Enable DNS-01 challenge provider for wildcard certificates
    - dns01:
        cloudflare:
          email: admin@example.com  # Replace with your Cloudflare email
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
      selector:
        dnsNames:
        - "*.example.com"
        - "*.api.example.com"
---
# Self-signed issuer for internal certificates
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  labels:
    app: cert-manager
    environment: development
spec:
  selfSigned: {}
---
# CA issuer for internal PKI
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
  labels:
    app: cert-manager
    environment: internal
spec:
  ca:
    secretName: ca-key-pair
---
# Vault issuer for enterprise PKI (optional)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
  labels:
    app: cert-manager
    environment: enterprise
spec:
  vault:
    server: https://vault.example.com:8200
    path: pki/sign/example-dot-com
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cert-manager
        secretRef:
          name: cert-manager-vault-token
          key: token
---
# Secret for Cloudflare API token (create manually or via External Secrets Operator)
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
data:
  # Base64 encoded Cloudflare API token
  # Replace with: echo -n "your-cloudflare-api-token" | base64
  api-token: eW91ci1jbG91ZGZsYXJlLWFwaS10b2tlbg==
---
# Secret for CA key pair (for CA issuer)
apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
  namespace: cert-manager
type: kubernetes.io/tls
data:
  # Generate with:
  # openssl genrsa -out ca.key 4096
  # openssl req -new -x509 -key ca.key -sha256 -subj "/C=US/ST=CA/O=MyOrg/CN=MyCA" -days 3650 -out ca.crt
  # kubectl create secret tls ca-key-pair --cert=ca.crt --key=ca.key --dry-run=client -o yaml
  tls.crt: LS0tLS1CRUdJTi... # Base64 encoded CA certificate
  tls.key: LS0tLS1CRUdJTi... # Base64 encoded CA private key

