# HashiCorp Vault SecretStore
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: default
spec:
  provider:
    vault:
      server: "https://vault.example.com:8200"
      path: "secret"
      version: "v2"
      auth:
        # Option 1: Kubernetes Service Account Token
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets-vault-sa
        # Option 2: AppRole authentication
        # appRole:
        #   path: "approle"
        #   roleId: "role-id-here"
        #   secretRef:
        #     name: vault-secret
        #     key: secretKey
        # Option 3: JWT/OIDC authentication
        # jwt:
        #   path: "jwt"
        #   role: "external-secrets"
        #   serviceAccountRef:
        #     name: external-secrets-vault-sa
---
# ClusterSecretStore for Vault (cluster-wide)
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend-cluster
spec:
  provider:
    vault:
      server: "https://vault.example.com:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets-vault-sa
            namespace: external-secrets-system
---
# Service Account for Vault authentication
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-vault-sa
  namespace: default
---
# Example ExternalSecret using Vault KV v2
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-database-secret
  namespace: default
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: vault-database-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        connection-url: "postgresql://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .database }}"
  data:
  - secretKey: username
    remoteRef:
      key: database/prod
      property: username
  - secretKey: password
    remoteRef:
      key: database/prod
      property: password
  - secretKey: host
    remoteRef:
      key: database/prod
      property: host
  - secretKey: port
    remoteRef:
      key: database/prod
      property: port
  - secretKey: database
    remoteRef:
      key: database/prod
      property: database
---
# Vault Dynamic Secrets (Database credentials)
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-dynamic-db
  namespace: default
spec:
  provider:
    vault:
      server: "https://vault.example.com:8200"
      path: "database"
      version: "v1"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets-vault-sa
---
# ExternalSecret for dynamic database credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dynamic-db-credentials
  namespace: default
spec:
  refreshInterval: 1h  # Refresh every hour for dynamic secrets
  secretStoreRef:
    name: vault-dynamic-db
    kind: SecretStore
  target:
    name: dynamic-db-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: creds/postgres-role
      property: username
  - secretKey: password
    remoteRef:
      key: creds/postgres-role
      property: password
---
# Vault PKI for certificate management
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-pki
  namespace: default
spec:
  provider:
    vault:
      server: "https://vault.example.com:8200"
      path: "pki"
      version: "v1"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: external-secrets-vault-sa
---
# ExternalSecret for PKI certificates
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-pki-cert
  namespace: default
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: vault-pki
    kind: SecretStore
  target:
    name: vault-pki-cert
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .certificate }}"
        tls.key: "{{ .private_key }}"
  data:
  - secretKey: certificate
    remoteRef:
      key: issue/example-dot-com
      property: certificate
  - secretKey: private_key
    remoteRef:
      key: issue/example-dot-com
      property: private_key

