apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: istio
  annotations:
    description: "Istio Gateway Controller for production workloads"
spec:
  controllerName: istio.io/gateway-controller
  description: "Gateway class for Istio service mesh"
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: istio-internal
  annotations:
    description: "Istio Gateway Controller for internal services"
spec:
  controllerName: istio.io/gateway-controller
  description: "Gateway class for internal Istio gateways"
  parametersRef:
    group: ""
    kind: ConfigMap
    name: istio-internal-config
    namespace: istio-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-internal-config
  namespace: istio-system
data:
  service.type: "ClusterIP"
  service.annotations: |
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
